import read_packet
import time


while True:
    read_packet.analyze_pcap("s1-eth1_in")
    read_packet.analyze_pcap("s1-eth2_in")
    read_packet.analyze_pcap("s1-eth3_in")
    read_packet.analyze_pcap("s2-eth1_in")
    read_packet.analyze_pcap("s2-eth2_in")
    read_packet.analyze_pcap("s2-eth3_in")
    read_packet.analyze_pcap("s3-eth1_in")
    read_packet.analyze_pcap("s3-eth2_in")
    read_packet.analyze_pcap("s3-eth3_in")
    read_packet.analyze_pcap("s1-eth1_out")
    read_packet.analyze_pcap("s1-eth2_out")
    read_packet.analyze_pcap("s1-eth3_out")
    read_packet.analyze_pcap("s2-eth1_out")
    read_packet.analyze_pcap("s2-eth2_out")
    read_packet.analyze_pcap("s2-eth3_out")
    read_packet.analyze_pcap("s3-eth1_out")
    read_packet.analyze_pcap("s3-eth2_out")
    read_packet.analyze_pcap("s3-eth3_out")
    print("read s1-eth1_in")
    read_packet.read_and_save("s1-eth1_in")
    print("read s1-eth2_in")
    read_packet.read_and_save("s1-eth2_in")
    print("read s1-eth3_in")
    read_packet.read_and_save("s1-eth3_in")
    print("read s2-eth1_in")
    read_packet.read_and_save("s2-eth1_in")
    print("read s2-eth2_in")
    read_packet.read_and_save("s2-eth2_in")
    print("read s2-eth3_in")
    read_packet.read_and_save("s2-eth3_in")
    print("read s3-eth1_in")
    read_packet.read_and_save("s3-eth1_in")
    print("read s3-eth2_in")
    read_packet.read_and_save("s3-eth2_in")
    print("read s3-eth3_in")
    read_packet.read_and_save("s3-eth3_in")

    print("read s1-eth1_out")
    read_packet.read_and_save("s1-eth1_out")
    print("read s1-eth2_out")
    read_packet.read_and_save("s1-eth2_out")
    print("read s1-eth3_out")
    read_packet.read_and_save("s1-eth3_out")
    print("read s2-eth1_out")
    read_packet.read_and_save("s2-eth1_out")
    print("read s2-eth2_out")
    read_packet.read_and_save("s2-eth2_out")
    print("read s2-eth3_out")
    read_packet.read_and_save("s2-eth3_out")
    print("read s3-eth1_out")
    read_packet.read_and_save("s3-eth1_out")
    print("read s3-eth2_out")
    read_packet.read_and_save("s3-eth2_out")
    print("read s3-eth3_out")
    read_packet.read_and_save("s3-eth3_out")

    print("**************************************")
    print("turn")
    print("**************************************")
    time.sleep(1)
